export enum IconFilterEnum {
  ICON_FILTER_ACTOR = "ICON_FILTER_ACTOR",
ICON_FILTER_WORKOBJECT = "ICON_FILTER_WORKOBJECT",
ICON_FILTER_UNASSIGNED = "ICON_FILTER_UNASSIGNED",
ICON_FILTER_NONE = "ICON_FILTER_NONE",
}
